### DISCUSSION TITLE
Deploying lambdas in ci/cd

### DISCUSSION THREAD

**Discussion by sondrelg** [cargo-lambda/cargo-lambda#384] [Q&A]
Hi,

First of all thanks for creating and maintaining this package. It's been incredibly helpful! :clap: 

I'm new to working with lambdas in general, and I've been trying to figure out what the most ergonomic way of setting up automated deployments would be. Since running `cargo lambda deploy <function>` was so incredibly easy locally, I thought that seemed like a good option for CI.

When trying to set up deployments from Github actions I probably spent a few more hours than I needed to, because I made simple mistakes like not immediately giving my service account enough permissions, I forgot to specify the `AWS_DEFAULT_REGION` environment variable, and so on.

I just quickly wanted to ask:

1. First, Is deploying from CI/CD pipelines generally encouraged and considered a good practice? Would you advise other methods than `cargo-lambda` for this, or is that fine? :slightly_smiling_face: 

2. If yes, do you think explaining how to deploy a lambda from CI in the docs of `cargo-lambda` would be beneficial for users of `cargo-lambda`? I guess there is less value in documenting how to set up a workflow for individual CI providers, but the AWS side of things seems generally applicable.

------------

What I ended up needing to get things to work, was a service account with these permissions

```terraform
resource "aws_iam_user" "lambda-service-user" {
  name = "lambda-service-user"
}

resource "aws_iam_access_key" "lambda-service-user" {
  user = aws_iam_user.lambda-service-user.name
}

resource "aws_iam_policy" "lambda-service-policy" {
  name   = "lambda-service-policy"
  policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "lambda:GetFunction",
          "lambda:CreateFunction",
          "lambda:UpdateFunctionCode",
          "lambda:UpdateFunctionConfiguration",
          "lambda:PublishVersion",
          "lambda:TagResource"
        ]
        Resource = [
          "arn:aws:lambda:<region>:<account-id>:function:<function-name>",
        ]
      }
    ]
  })
}

resource "aws_iam_user_policy_attachment" "lambda-service-user-policy-attachment" {
  user       = aws_iam_user.lambda-service-user.name
  policy_arn = aws_iam_policy.lambda-service-policy.arn
}
```

(there may be one or two more here than is strictly needed, will find out when I'm done testing)

And this is the relevant part of  my github action workflow:

```yaml
- run: |
    pip install cargo-lambda
    cargo lambda build -p aircall --release --arm64
    cargo lambda deploy aircall
  env:
    AWS_DEFAULT_REGION: <region>
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  if: github.event_name == 'push'
```

I would totally understand if this seems just out of scope for the docs of the package. At least then, now if someone searches for `AWS_ACCESS_KEY_ID` in the issue tracker there will be something there for them :slightly_smiling_face:
