### DISCUSSION TITLE
Docker "Address not available"

### DISCUSSION THREAD

**Discussion by drieshooghe** [cargo-lambda/cargo-lambda#427] [Q&A]
Hi

I've created a simple Dockerfile in which I wanted to run `cargo lambda watch`.

The Dockerfile
```Dockerfile
FROM rust:alpine

WORKDIR /app

RUN apk update && \
	apk add musl-dev

RUN cargo install cargo-lambda

COPY ./ ./

EXPOSE 9000
```

And in my Docker-compose file it gets started like this:
```yml
  projects:
    build: ./projects
    ports:
      - "9000:9000"
    volumes:
      - ./projects:/app
    command: sh -c "cargo lambda watch"
```

I can invoke the Lambda by sending a request to `http://0.0.0.0:9000/lambda-url/projects/`, but after it gets built it throws the following error
```sh
Error: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Address not available" }))
```
Perhaps related, if I run it on my Mac it gives me the following prompt:
![image](https://user-images.githubusercontent.com/25033847/225390335-525baeee-4070-416e-8954-2e5270d48b61.png)
