### ISSUE TITLE
How to define endpoint route?

### ISSUE THREAD

**Issue by winston0410** [cargo-lambda/cargo-lambda#164]
I am trying to migrate from `serverless-rust` to `cargo-lambda`, for deploying incrementally. One thing I cannot find in README is the way to define route and endpoint with `cargo-lambda`. How can I provider the following information?

This would be the config for `serverless`

```yaml
functions:
  # handler value syntax is `{cargo-package-name}.{bin-name}`
  # or `{cargo-package-name}` for short when you are building a
  # default bin for a given package.
  hello:
    handler: hello
    events:
      - httpApi:
          path: /v1/hello
          method: get
```
