### ISSUE TITLE
Deploy doesn't work in workspace

### ISSUE THREAD

**Issue by drager** [cargo-lambda/cargo-lambda#185]
Hey, it seems like `cargo-lambda` can't deploy things in a workspace?

tree:
```
├── Cargo.lock
├── Cargo.toml
├── crates
│   ├── app_1
│   │   ├── Cargo.toml
│   │   └── src
│   ├── app_2
│   │   ├── Cargo.toml
│   │   └── src
│   ├── app_3
│   │   ├── Cargo.toml
│   │   ├── migrations
│   │   └── src
├── src
│   ├── config.rs
│   ├── lib.rs
│   ├── notifier.rs
```

`app_2` is the only one that has a lambda and depends on `lambda_http` etc.

root Cargo.toml:
```toml
[package]
name = "project"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 2

[workspace]
members = ["crates/*"]
```

Running `cargo lambda deploy --iam-role arn:aws:iam::610581918146:role/AWS_LAMBDA_FULL_ACCESS app_2` gives me `Error: 
  × binary file for app_2 not found, use `cargo lambda build` to create it`

If I take the `app_2` and move it to another folder outside of this workspace and builds, then `cargo-lambda` is able to deploy it.
