### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by calavera** [cargo-lambda/cargo-lambda#231]
It'd be nice to provide a GitHub Action that uses the Docker Image described in #230. That way people that want to use Cargo Lambda in GitHub Actions don't have to worry about installing it.

We'd probably need a new repository in the org for that.

**Comment by zerj9** [comment]
Is this something that could work? [setup-cargo-lambda](https://github.com/marketplace/actions/setup-cargo-lambda)

Doesn't run in a Docker container though. I've just used the [Developing a third party CLI action](https://docs.github.com/en/actions/creating-actions/developing-a-third-party-cli-action) guide to download the binary and make it usable inside a job.

**Comment by rherrmannr** [comment]
I've tried using `pip3 install cargo-lambda`, but wasn't able to use it in GitHub Action. [This](https://github.com/marketplace/actions/setup-cargo-lambda) worked for me! Thanks

**Comment by rherrmannr** [comment]
Y

**Comment by rherrmannr** [comment]
Just as a hint, zig is required:
```
- uses: goto-bus-stop/setup-zig@v2
- name: Install Cargo Lambda
  uses: jaxxstorm/action-install-gh-release@v1.9.0
  with:
    repo: cargo-lambda/cargo-lambda
    tag: v0.14.0
    platform: linux
    arch: x86_64
```
