### ISSUE TITLE
Error when running the function

### ISSUE THREAD

**Issue by dimas-cyriaco** [cargo-lambda/cargo-lambda#258]
I created a test project following the video tutorial, and when I invoke the function I receive the error:

```
Error("data did not match any variant of untagged enum LambdaRequest", line: 0, column: 0)
```

The same thing occurs when deploying and accessing the function url.

The exact steps I did:

```sh
cargo lambda new http-lambda
cd http-lamda
cargo lambda build --release --arm64
cargo lambda deploy --enable-function-url
```

The deployed function didn't work. Then I did:

```sh
cargo lambda watch
```

And accessed `http://localhost:9000/lambda-url/http-lambda/`. Received the same error message in the terminal and this message on the browser:

```
{"type":"https://httpstatuses.com/500","status":500,"title":"Internal Server Error","detail":"failed to serialize lambda-url event"}
```

I'm on cargo version `cargo 1.63.0 (fd9c4297c 2022-07-01)`.
These are the dependencies:
```toml
[dependencies]
lambda_http = { version = "0.6.1", default-features = false, features = ["apigw_rest"] }
lambda_runtime = "0.6.1"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
```

Any help is welcomed.
