### ISSUE TITLE
CI process is not proceeding

### ISSUE THREAD

**Issue by ramunecroft** [cargo-lambda/cargo-lambda#554]
```yaml
name: Rust

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

env:
  TEMPLATE_FILE: template.yaml
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache

      - name: Setup aws-sam
        uses: aws-actions/setup-sam@v2

      - name: Release lambda
        run: |
          pip install cargo-lambda
          sam build --beta-features --use-container 
          sam deploy --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset --no-fail-on-empty-changeset
        env:
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

First of all, thank you for creating a great library.

My issue is that the Release lambda is no longer progressing and remains indefinitely in a pending state.

I've waited for a while, but it doesn't proceed. Is there something wrong?

<img width="1511" alt="image" src="https://github.com/cargo-lambda/cargo-lambda/assets/119154327/fcb15276-1e22-4741-8aa9-045bb0a2e173">
