### ISSUE TITLE
deserialization failure at command line, and from invoke().send() but not console test

### ISSUE THREAD

**Issue by rseymour** [cargo-lambda/cargo-lambda#569]
This is likely a multifaceted issue, possibly stemming from my SAM Template, but I have 1 API Gateway fronted lambda which works perfectly.  In order to process something that takes over 29 seconds, I needed to create a second lambda which processses events asyncronously.

From the console test page, I can send JSON and dbg!() the event payload. 

The type for the event is widely used in the working lambda so I'm pretty sure that isn't the problem.  Oddly when I invoke from another lambda with the following code:
```        
        let sdk_config = aws_config::load_from_env().await;
        let lclient = aws_sdk_lambda::Client::new(&sdk_config);
        match lclient
            .invoke()
            .function_name("**function name**")
            .invocation_type(aws_sdk_lambda::types::InvocationType::Event)
            .payload(Blob::new(value_of_my_payload_type.to_json_string()))
            .send()
            .await
```
The caller logs no error (normal and good for an async call), but the receiver logs:
```
Error: lambda_runtime::deserializer::DeserializeError

  × failed to deserialize the incoming data into the function's payload type: invalid type: map, expected unit at line 1 column 0
```

The reproducible thing is that `cargo lambda invoke --remote` returns the same error (in fact that's where I got the pretty printed version above from).

`cargo lambda invoke` on the local function works fine. 

This pretty much narrows it down to some sort of issue between the configuration and the code, because the `invalid type` log prints before my little  `dbg!()` at the top of the `main` function, not even the handler.

My SAM template (I know this is getting out of the cargo-lambda wheelhouse) is just:
```
  MyFunc: # why is there no Event Event... or Async Event type?
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: my_func_binary_name_lined_up_from_cargo.toml
    Properties:
      # environment vars and policies redacted
      CodeUri: ./my_func
      Handler: bootstrap
      Runtime: provided.al2
```
What's weird to me is the lack of an `Events` field, ie what is supposed to trigger this thing.  But then when I look in the list of triggers I don't see "async invoke" or even "plain invoke" so I'm assuming it's a baked in default.

So yea, did I write some code that expects () instead of json and it got cached somewhere? I can't figure out how this would work 2 ways (local and through the console test), but not 2 other ways.  The service_fn stuff looks like:

```    
    let func = service_fn(move |event| async move { function_handler(event).await });
    lambda_runtime::run(func).await?;
```

Putting the `move |event|` closure seemed necessary to make this work, and indeed I may need to a pass a database connection to the `function_handler` as well once I get this figured out.

I realize this isn't likely a pure cargo-lambda issue, you're tooling has really made working with rust + aws super nice.  Thanks for that, I'm sure I'll figure this out but I'd appreciate any ideas.
