### ISSUE TITLE
"there are more than one binary in the project, you must specify a binary name" error on deploy since v1.0.1

### ISSUE THREAD

**Issue by oeed** [cargo-lambda/cargo-lambda#596]
My GitHub Actions builds have recently started failing. They work when pinning cargo-lambda to v1.0.0. I don't believe there should be more than one binary, unless multiple can now be created? I can't see any obvious cause in the change log.

For reference, the GH Action (irrelevant in-between steps removed):
```yml

- name: Install Cargo Lambda
  uses: jaxxstorm/action-install-gh-release@v1.9.0
  with:
    repo: cargo-lambda/cargo-lambda
    platform: linux
    arch: x86_64

- name: Build Lambda Binary
  run: cargo lambda build --release --target x86_64-unknown-linux-gnu.2.26
  env:
    RELEASE_NAME: ${{ inputs.release-name }}

- name: Deploy Lambda Binary
  id: deploy
  run: cargo lambda deploy --env-file .env | tee >(echo "VERSION=$(grep -oP 'arn:aws:lambda:.*:.*:function:.*:\K\d+')" >> $GITHUB_OUTPUT)
```

Deploy output with v1.0.0:
```
Run cargo lambda deploy --env-file .env | tee >(echo "VERSION=$(grep -oP 'arn:aws:lambda:.*:.*:function:.*:\K\d+')" >> $GITHUB_OUTPUT)
▹▹▹▹▹ loading binary data
▹▹▹▹▹ deploying function
🔍 function arn: arn:aws:lambda:***:***:function:***:***
```

Deploy output with v1.0.1:
```
Run cargo lambda deploy --env-file .env | tee >(echo "VERSION=$(grep -oP 'arn:aws:lambda:.*:.*:function:.*:\K\d+')" >> $GITHUB_OUTPUT)
▹▹▹▹▹ loading binary data
Error:   × there are more than one binary in the project, you must specify a binary
  │ name

  Was this error unexpected?
  Open an issue in https://github.com/cargo-lambda/cargo-lambda/issues
```
