### ISSUE TITLE
`cargo lambda watch` does not support `--no-default-features`

### ISSUE THREAD

**Issue by miceg** [cargo-lambda/cargo-lambda#688]
I'm porting a project which runs as a stand-alone HTTP server to also run with Lambda.

The stand-alone HTTP server **must** remain the default build mode for compatibility reasons, so I've setup `Cargo.toml` with a `[features]` block:

```toml
[features]
default = ["http-server"]
http-server = []
lambda = ["dep:lambda_http", "dep:lambda_runtime"]
```

`cargo lambda build` supports `--no-default-features`, but `cargo lambda watch` does not.

I also tried using a `[package.metadata.lambda.build]` config:

```toml
[package.metadata.lambda.build]
compiler.type = "cargo"
compiler.extra_args = ["--no-default-features", "--features", "lambda"]
```

But this does not affect `cargo lambda watch`.

I considered removing the `http-server` feature and instead trigger that when `#[cfg(not(feature = "lambda"))]`, but this would violate [the principle that features are additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification), and pull in dependencies which are not relevant in a Lambda environment.
