### ISSUE TITLE
Set the default features when using cargo lambda build or cargo lambda watch.

### ISSUE THREAD

**Issue by jifalops** [cargo-lambda/cargo-lambda#732]
My crate has `lambda` as a feature that is not enabled by default. I can enable it on the command line easily by using `--features`, but I can't figure out how to get `sam build` to pass args to `cargo lambda build`.

Is there something I can put in Cargo.toml? I've tried:
```toml
[package.metadata.lambda.build]
[package.metadata.lambda.watch]
features = "lambda"
```
#688 has
```toml
[package.metadata.lambda.build]
compiler.type = "cargo"
compiler.extra_args = ["--no-default-features", "--features", "lambda"]
```

but I'm not sure if I should change the compiler. 

I'm looking for a little guidance on using "config as code" for crate features. If it is possible it doesn't appear to be documented.
