### ISSUE TITLE
package metadata defined in a workspace not utilized

### ISSUE THREAD

**Issue by rtyler** [cargo-lambda/cargo-lambda#864]
I have a feeling this is a bug but I'm still not certain where it might live 🐛  When using `cargo-lambda` inside of a workspace project, the setting of project-specific metadata in `Cargo.toml` doesn't seem to apply.

For example, if I use the following in a `member/Cargo.toml`

```toml
[package.metadata.lambda.build]
output_format = "zip"
features = ["lol"]
```

This will not be read by `cargo lambda build`.

Workspace level configuration in `./Cargo.toml` does work, but of course `features` cannot be defined in the workspace 😦 

```toml
[workspace.metadata.lambda.build]
output_format = "zip"
```
